### ISSUE TITLE
Kernel check doesn't work properly

### ISSUE THREAD

**Issue by phunni** [wiemag/arch-headless#2]
When attempting to run arch-headless I get the following error:

> Kernel installed: 5.3.13.1-1  
> Kernel running:   5.3.13-arch1-1  
> Mounting not possible.  
> Your computer needs to be rebooted.  

The kernels are the same and there really isn't a need to reboot. I've worked around it for now by editing the script, but it's still an issue.

**Comment by wiemag** [comment]
Fixed.
A lot has changed in Arch Linux since four years ago, and this is one of those things.
